import Head from "next/head";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Paytone+One&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap"
        />
        <meta name="robots" content="noindex,nofollow" />
      </Head>
      <body className="antialiased bg-[#E6EBF4] overflow-x-hidden">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
